"""Shared fixtures for visual quality tests."""

import json
import os
import pytest

RESEARCH_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GROUND_TRUTH_PATH = os.path.join(RESEARCH_DIR, "visual_ground_truth.json")


@pytest.fixture(scope="session")
def ground_truth():
    """Load the visual ground truth JSON generated by visual_oracle.py."""
    if not os.path.exists(GROUND_TRUTH_PATH):
        pytest.skip(
            f"Ground truth not found at {GROUND_TRUTH_PATH}. "
            "Run: python research/visual_oracle.py"
        )
    with open(GROUND_TRUTH_PATH) as f:
        return json.load(f)
