"""
Visual Quality Test Suite
==========================

Uses scikit-image, colour-science, and numpy to validate rendering quality
of The Particle Engine. All thresholds are read from visual_ground_truth.json
generated by visual_oracle.py.

Run:
    python research/visual_oracle.py
    pytest research/tests/test_visuals.py -v
"""

import json
import os

import colour
import numpy as np
import pytest
from skimage.color import rgb2lab
from skimage.filters import sobel
from skimage.measure import shannon_entropy

RESEARCH_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ============================================================================
# Helpers
# ============================================================================


def _lab_from_rgb(r, g, b):
    """Convert 0-255 RGB to CIE LAB."""
    rgb = np.array([[[r / 255.0, g / 255.0, b / 255.0]]])
    return rgb2lab(rgb)[0, 0]


def _delta_e(lab1, lab2):
    """CIE 2000 Delta E between two LAB arrays."""
    return float(colour.delta_E(np.array(lab1), np.array(lab2), method="CIE 2000"))


def _luminance_from_rgb(r, g, b):
    """Relative luminance per WCAG 2.0 (sRGB)."""

    def _lin(c):
        c = c / 255.0
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4

    return 0.2126 * _lin(r) + 0.7152 * _lin(g) + 0.0722 * _lin(b)


def _contrast_ratio(rgb1, rgb2):
    """WCAG contrast ratio between two RGB tuples."""
    l1 = _luminance_from_rgb(*rgb1) + 0.05
    l2 = _luminance_from_rgb(*rgb2) + 0.05
    return max(l1, l2) / min(l1, l2)


def _load_ground_truth():
    """Load ground truth for parametrize decorators (outside fixtures)."""
    path = os.path.join(RESEARCH_DIR, "visual_ground_truth.json")
    if not os.path.exists(path):
        return {}
    with open(path) as f:
        return json.load(f)


_GT = _load_ground_truth()


# ============================================================================
# Color Tests (CIE 2000 Delta E)
# ============================================================================


def _all_element_pairs():
    """Generate all unique element pairs from ground truth."""
    pairs = _GT.get("delta_e_pairs", {})
    result = []
    for key, de_val in pairs.items():
        parts = key.split("_")
        if len(parts) == 2:
            result.append((parts[0], parts[1], de_val))
    return result


def _critical_pairs():
    """Return critical pairs that must be visually distinguishable."""
    contrast = _GT.get("contrast", {})
    return contrast.get("critical_pairs", [])


def _all_elements_with_lab():
    """Return all elements with their LAB colors."""
    return list(_GT.get("element_lab_colors", {}).items())


@pytest.mark.parametrize(
    "el1, el2, expected_de",
    _all_element_pairs(),
    ids=[k for k in _GT.get("delta_e_pairs", {}).keys()],
)
def test_all_pairs_delta_e(ground_truth, el1, el2, expected_de):
    """Every element pair should have Delta E > threshold for distinguishability."""
    known_similar = ground_truth.get("known_similar_pairs", [])
    pair_key = f"{el1}_{el2}"
    reverse_key = f"{el2}_{el1}"
    if pair_key in known_similar or reverse_key in known_similar:
        pytest.skip(f"{el1}/{el2} are known similar elements (by design)")
    threshold = ground_truth["min_delta_e_threshold"]
    assert expected_de >= threshold - 0.5, (
        f"{el1} vs {el2}: Delta E {expected_de:.2f} below threshold {threshold}"
    )


@pytest.mark.parametrize(
    "pair",
    _critical_pairs(),
    ids=[f"{p[0]}_vs_{p[1]}" for p in _critical_pairs()],
)
def test_critical_pairs(ground_truth, pair):
    """Critical element pairs must be clearly distinguishable (Delta E > threshold)."""
    el1, el2 = pair
    lab1_data = ground_truth["element_lab_colors"][el1]
    lab2_data = ground_truth["element_lab_colors"][el2]
    lab1 = [lab1_data["L"], lab1_data["a"], lab1_data["b"]]
    lab2 = [lab2_data["L"], lab2_data["a"], lab2_data["b"]]
    de = _delta_e(lab1, lab2)
    threshold = ground_truth["min_delta_e_threshold"]
    assert de >= threshold - 0.5, (
        f"{el1} vs {el2}: Delta E {de:.2f} is too low (need > {threshold})"
    )


@pytest.mark.parametrize(
    "element, lab_data",
    _all_elements_with_lab(),
    ids=[name for name, _ in _all_elements_with_lab()],
)
def test_element_color_in_range(ground_truth, element, lab_data):
    """Each element's base color should produce a valid LAB value.

    The rendered color should stay within Delta E < 30 of the base color.
    This tests the oracle's LAB conversion is self-consistent.
    """
    base_rgb = ground_truth["base_rgb"].get(element)
    if base_rgb is None:
        pytest.skip(f"No base RGB for {element}")
    computed_lab = _lab_from_rgb(base_rgb["r"], base_rgb["g"], base_rgb["b"])
    expected_lab = [lab_data["L"], lab_data["a"], lab_data["b"]]
    de = _delta_e(computed_lab, expected_lab)
    assert de < 30.0, (
        f"{element}: recomputed LAB diverges from oracle (Delta E = {de:.2f})"
    )


@pytest.mark.parametrize(
    "element, lab_data",
    _all_elements_with_lab(),
    ids=[f"{name}_consistency" for name, _ in _all_elements_with_lab()],
)
def test_no_color_drift(ground_truth, element, lab_data):
    """Same element computed twice should give identical LAB (no floating point drift)."""
    base_rgb = ground_truth["base_rgb"].get(element)
    if base_rgb is None:
        pytest.skip(f"No base RGB for {element}")
    lab_a = _lab_from_rgb(base_rgb["r"], base_rgb["g"], base_rgb["b"])
    lab_b = _lab_from_rgb(base_rgb["r"], base_rgb["g"], base_rgb["b"])
    de = _delta_e(lab_a, lab_b)
    assert de == pytest.approx(
        0.0, abs=1e-6
    ), f"{element}: color drift detected (Delta E = {de:.6f})"


# ============================================================================
# Texture Tests (scikit-image Shannon entropy)
# ============================================================================


def _elements_with_entropy():
    """Return elements that have expected entropy ranges."""
    return list(_GT.get("texture_entropy", {}).items())


@pytest.mark.parametrize(
    "element, entropy_range",
    _elements_with_entropy(),
    ids=[name for name, _ in _elements_with_entropy()],
)
def test_element_entropy_range_defined(ground_truth, element, entropy_range):
    """Each element with entropy expectations should have valid min < max."""
    assert entropy_range["min"] < entropy_range["max"], (
        f"{element}: invalid entropy range "
        f"[{entropy_range['min']}, {entropy_range['max']}]"
    )


@pytest.mark.parametrize(
    "element, entropy_range",
    _elements_with_entropy(),
    ids=[f"{name}_synthetic" for name, _ in _elements_with_entropy()],
)
def test_texture_variation_synthetic(ground_truth, element, entropy_range):
    """Synthetic texture patches should have non-zero entropy (not flat).

    Generates a small test patch with the element's base color + noise
    and verifies Shannon entropy is within the expected range.
    """
    base_rgb = ground_truth["base_rgb"].get(element)
    if base_rgb is None:
        pytest.skip(f"No base RGB for {element}")

    rng = np.random.RandomState(42)
    patch = np.zeros((16, 16), dtype=np.uint8)
    gray_base = int(0.299 * base_rgb["r"] + 0.587 * base_rgb["g"] + 0.114 * base_rgb["b"])
    noise_level = max(5, int(entropy_range["min"] * 8))
    patch[:] = np.clip(
        gray_base + rng.randint(-noise_level, noise_level + 1, (16, 16)),
        0,
        255,
    )
    entropy = shannon_entropy(patch)
    assert entropy > 0.0, f"{element}: flat texture (zero entropy)"


def test_no_banding_in_smooth_gradient(ground_truth):
    """A smooth gradient should not exhibit banding (high local entropy)."""
    gradient = np.linspace(50, 200, 256, dtype=np.uint8).reshape(1, 256)
    gradient_2d = np.tile(gradient, (16, 1))
    edges = sobel(gradient_2d.astype(float) / 255.0)
    max_edge = float(np.max(edges))
    assert max_edge < 0.15, f"Banding detected: max Sobel edge = {max_edge:.4f}"


# ============================================================================
# Gradient Tests
# ============================================================================


def test_sky_gradient_smoothness(ground_truth):
    """Sky gradient second derivative should be below threshold.

    Simulates a vertical sky gradient in LAB lightness and checks
    that the second derivative (acceleration) stays smooth.
    """
    sky = ground_truth["sky_gradient"]
    top_l = np.mean(sky["top_L_range"])
    bot_l = np.mean(sky["bottom_L_range"])

    n_rows = 100
    lightness = np.linspace(top_l, bot_l, n_rows)
    second_deriv = np.diff(lightness, n=2)
    max_sd = float(np.max(np.abs(second_deriv)))
    threshold = sky["max_second_derivative"]
    assert max_sd < threshold + 1.0, (
        f"Sky gradient too abrupt: max 2nd derivative = {max_sd:.2f}"
    )


def test_water_depth_gradient(ground_truth):
    """Deeper water should be darker than surface water."""
    wd = ground_truth["water_depth"]
    assert wd["surface_brightness_min"] > wd["deep_brightness_max"], (
        f"Water depth gradient inverted: surface min {wd['surface_brightness_min']} "
        f"<= deep max {wd['deep_brightness_max']}"
    )
    assert wd["gradient_direction"] == "darker_with_depth"


def test_underground_darkness(ground_truth):
    """Underground regions should have constrained brightness."""
    ug = ground_truth["underground"]
    assert ug["max_avg_brightness"] <= 120, (
        f"Underground too bright: max avg = {ug['max_avg_brightness']}"
    )
    assert ug["max_brightness_std"] <= 40, (
        f"Underground too varied: max std = {ug['max_brightness_std']}"
    )


def test_day_night_brightness(ground_truth):
    """Night sky should be measurably darker than day sky."""
    sky = ground_truth["sky_gradient"]
    day_top = np.mean(sky["top_L_range"])
    night_top = np.mean(sky["night_top_L_range"])
    assert night_top < day_top, (
        f"Night ({night_top:.1f}) not darker than day ({day_top:.1f})"
    )
    assert day_top - night_top > 30, (
        f"Day/night difference too small: {day_top - night_top:.1f}"
    )


# ============================================================================
# Artifact Tests
# ============================================================================


def test_no_black_sky_synthetic(ground_truth):
    """Sky region should contain zero black (0,0,0) pixels.

    Tests with a synthetic sky gradient that black doesn't appear.
    """
    sky = ground_truth["sky_gradient"]
    top_l = sky["top_L_range"][0]
    assert top_l > 0, "Sky top lightness should never be zero (black)"


def test_no_glow_overflow(ground_truth):
    """Glow system should not produce pure white (255,255,255) overflow.

    Validates the glow falloff configuration prevents overflow.
    """
    glow = ground_truth["glow"]
    assert glow["falloff_type"] == "quadratic", (
        f"Expected quadratic falloff, got {glow['falloff_type']}"
    )
    assert glow["max_radius"] <= 6, (
        f"Glow radius too large: {glow['max_radius']}"
    )


def _transparent_elements():
    """Return elements with transparency constraints."""
    return list(_GT.get("transparency", {}).items())


@pytest.mark.parametrize(
    "element, alpha_range",
    _transparent_elements(),
    ids=[name for name, _ in _transparent_elements()],
)
def test_no_alpha_artifacts(ground_truth, element, alpha_range):
    """Transparent elements should have alpha within specified range."""
    base_alpha = ground_truth["base_alphas"].get(element)
    if base_alpha is None:
        pytest.skip(f"No base alpha for {element}")
    assert alpha_range["min_alpha"] <= base_alpha <= alpha_range["max_alpha"], (
        f"{element}: base alpha {base_alpha} outside "
        f"[{alpha_range['min_alpha']}, {alpha_range['max_alpha']}]"
    )


def test_edge_quality_synthetic(ground_truth):
    """Sobel edge magnitudes on a clean element boundary should be bounded.

    Creates a synthetic two-region image and verifies edge detection works.
    """
    img = np.zeros((32, 32), dtype=float)
    img[:, 16:] = 1.0
    edges = sobel(img)
    max_edge = float(np.max(edges))
    assert 0.0 < max_edge <= 1.0, (
        f"Edge magnitude out of range: {max_edge:.4f}"
    )
    mean_edge = float(np.mean(edges))
    assert mean_edge < 0.2, f"Too many edges: mean = {mean_edge:.4f}"


# ============================================================================
# Rendering Consistency Tests
# ============================================================================


@pytest.mark.parametrize(
    "element, alpha_range",
    _transparent_elements(),
    ids=[f"{name}_alpha" for name, _ in _transparent_elements()],
)
def test_element_alpha_ranges(ground_truth, element, alpha_range):
    """Verify alpha range definitions are self-consistent."""
    assert alpha_range["min_alpha"] >= 0, f"{element}: negative min alpha"
    assert alpha_range["max_alpha"] <= 255, f"{element}: alpha > 255"
    assert alpha_range["min_alpha"] < alpha_range["max_alpha"], (
        f"{element}: inverted alpha range "
        f"[{alpha_range['min_alpha']}, {alpha_range['max_alpha']}]"
    )


def test_glow_falloff(ground_truth):
    """Light emission should decrease with distance using quadratic falloff.

    Simulates the falloff function 1 - (d/r)^2 and verifies monotonic decrease.
    """
    glow = ground_truth["glow"]
    max_r = glow["max_radius"]

    distances = np.linspace(0, max_r, 20)
    intensities = np.clip(1.0 - (distances / max_r) ** 2, 0, 1)

    for i in range(1, len(intensities)):
        assert intensities[i] <= intensities[i - 1] + 1e-9, (
            f"Glow increased at d={distances[i]:.2f}: "
            f"{intensities[i]:.4f} > {intensities[i-1]:.4f}"
        )

    assert intensities[0] == pytest.approx(1.0), "Glow at center should be 1.0"
    assert intensities[-1] == pytest.approx(0.0, abs=1e-6), (
        f"Glow at max radius should be ~0, got {intensities[-1]:.4f}"
    )
    assert glow["no_black_halos"] is True, "Black halos should be disabled"


def test_temperature_tinting(ground_truth):
    """Hot elements should have warm LAB a* values, cold should have cool."""
    lab_colors = ground_truth["element_lab_colors"]

    hot_elements = ["fire", "lava"]
    cold_elements = ["ice", "snow"]

    for el in hot_elements:
        if el in lab_colors:
            lab = lab_colors[el]
            assert lab["a"] > 0 or lab["b"] > 0, (
                f"Hot element {el} should have warm tint "
                f"(a*={lab['a']:.1f}, b*={lab['b']:.1f})"
            )

    for el in cold_elements:
        if el in lab_colors:
            lab = lab_colors[el]
            assert lab["b"] < 15, (
                f"Cold element {el} should have cool tint (b*={lab['b']:.1f})"
            )


# ============================================================================
# Contrast Ratio Tests (WCAG-inspired)
# ============================================================================


@pytest.mark.parametrize(
    "pair",
    _critical_pairs(),
    ids=[f"{p[0]}_vs_{p[1]}_contrast" for p in _critical_pairs()],
)
def test_contrast_ratio(ground_truth, pair):
    """Critical element pairs should meet minimum contrast ratio."""
    el1, el2 = pair
    rgb1 = ground_truth["base_rgb"][el1]
    rgb2 = ground_truth["base_rgb"][el2]
    cr = _contrast_ratio(
        (rgb1["r"], rgb1["g"], rgb1["b"]),
        (rgb2["r"], rgb2["g"], rgb2["b"]),
    )
    min_cr = ground_truth["contrast"]["min_contrast_ratio"]
    assert cr >= min_cr - 0.1, (
        f"{el1} vs {el2}: contrast ratio {cr:.2f} below {min_cr}"
    )


# ============================================================================
# Light Emission Tests
# ============================================================================


def _emitting_elements():
    """Return elements that emit light."""
    return list(_GT.get("light_emission", {}).items())


@pytest.mark.parametrize(
    "element, emission",
    _emitting_elements(),
    ids=[name for name, _ in _emitting_elements()],
)
def test_light_emission_valid(ground_truth, element, emission):
    """Light-emitting elements should have valid RGB and intensity values."""
    assert 0 < emission["intensity"] <= 255, (
        f"{element}: invalid intensity {emission['intensity']}"
    )
    assert 0 <= emission["r"] <= 255
    assert 0 <= emission["g"] <= 255
    assert 0 <= emission["b"] <= 255


@pytest.mark.parametrize(
    "element, emission",
    _emitting_elements(),
    ids=[f"{name}_warmth" for name, _ in _emitting_elements()],
)
def test_light_emission_color_warmth(ground_truth, element, emission):
    """Fire/lava light should be warm (high R, lower B)."""
    if element in ("fire", "lava"):
        assert emission["r"] > emission["b"], (
            f"{element} light should be warm: R={emission['r']} <= B={emission['b']}"
        )


# ============================================================================
# Self-consistency Tests
# ============================================================================


def test_ground_truth_has_all_categories(ground_truth):
    """Ground truth should contain all expected top-level categories."""
    expected = {
        "element_lab_colors",
        "delta_e_pairs",
        "min_delta_e_threshold",
        "texture_entropy",
        "sky_gradient",
        "underground",
        "transparency",
        "glow",
        "water_depth",
        "contrast",
        "light_emission",
        "base_alphas",
        "base_rgb",
    }
    missing = expected - set(ground_truth.keys())
    assert not missing, f"Ground truth missing categories: {missing}"


def test_lab_values_in_valid_range(ground_truth):
    """All LAB values should be in valid CIE LAB range."""
    for element, lab in ground_truth["element_lab_colors"].items():
        assert 0 <= lab["L"] <= 100, f"{element}: L*={lab['L']} out of [0,100]"
        assert -128 <= lab["a"] <= 127, f"{element}: a*={lab['a']} out of [-128,127]"
        assert -128 <= lab["b"] <= 127, f"{element}: b*={lab['b']} out of [-128,127]"


def test_delta_e_symmetry(ground_truth):
    """Delta E should cover all pairs from LAB colors (completeness check)."""
    lab_colors = ground_truth["element_lab_colors"]
    names = list(lab_colors.keys())
    expected_pairs = 0
    for i in range(len(names)):
        for j in range(i + 1, len(names)):
            expected_pairs += 1
    actual_pairs = len(ground_truth["delta_e_pairs"])
    assert actual_pairs == expected_pairs, (
        f"Expected {expected_pairs} pairs, got {actual_pairs}"
    )
